apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      # Control how Pods are spread across your cluster
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: nginx-webapp
      containers:
        - name: nginx
          image: nginx:1.14.2
          # Wait for the application to initialize
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              # For CPU resource units, the quantity expression 0.1 is equivalent to the expression 100m
              cpu: 100m
              memory: "128M"
            limits:
              cpu: 100m
              memory: "128M"
          ports:
            - containerPort: 80